import { describe, it, expect } from 'vitest';
import { generateExample } from '../src/generate.js';
import type { Schema } from '../src/types.js';

describe('generateExample', () => {
  const schema: Schema = {
    PORT: { type: 'port', required: true, description: 'Server port', example: '3000' },
    DATABASE_URL: { type: 'url', required: true, description: 'PostgreSQL connection string' },
    NODE_ENV: {
      type: 'enum',
      values: ['development', 'production', 'test'],
      default: 'development',
      description: 'Node environment',
    },
    OPTIONAL_KEY: {
      type: 'string',
      description: 'An optional setting',
      example: 'some-value',
      minLength: 3,
      maxLength: 50,
    },
  };

  it('returns string content', () => {
    const content = generateExample(schema, '__test__');
    expect(typeof content).toBe('string');
    expect(content.length).toBeGreaterThan(0);
  });

  it('includes header', () => {
    const content = generateExample(schema, '__test__');
    expect(content).toContain('# Environment Variables');
    expect(content).toContain('Generated by env-doctor');
  });

  it('includes required vars uncommented', () => {
    const content = generateExample(schema, '__test__');
    expect(content).toContain('PORT=');
    expect(content).toContain('DATABASE_URL=');
  });

  it('includes optional vars commented', () => {
    const content = generateExample(schema, '__test__');
    expect(content).toContain('# OPTIONAL_KEY=');
  });

  it('includes defaults as comments', () => {
    const content = generateExample(schema, '__test__');
    // NODE_ENV is optional with default, so it should be commented
    expect(content).toContain('NODE_ENV=');
  });

  it('includes descriptions', () => {
    const content = generateExample(schema, '__test__');
    expect(content).toContain('Server port');
    expect(content).toContain('PostgreSQL connection string');
  });

  it('includes type annotations', () => {
    const content = generateExample(schema, '__test__');
    expect(content).toContain('Type: port');
    expect(content).toContain('Type: url');
    expect(content).toContain('Type: enum');
  });

  it('includes constraints (required, minLength, etc)', () => {
    const content = generateExample(schema, '__test__');
    expect(content).toContain('required');
    expect(content).toContain('min 3 chars');
    expect(content).toContain('max 50 chars');
  });

  it('uses provided example value', () => {
    const content = generateExample(schema, '__test__');
    expect(content).toContain('PORT=3000');
  });

  it('handles single-field schema', () => {
    const content = generateExample({ FOO: { type: 'string', required: true } }, '__test__');
    expect(content).toContain('FOO=');
  });

  it('handles empty schema', () => {
    const content = generateExample({}, '__test__');
    expect(content).toBeTruthy();
  });
});
