import * as fs from 'node:fs';
import * as path from 'node:path';
import type { Schema } from './types.js';

export function generateExample(schema: Schema, outputPath?: string): string {
  const lines: string[] = [];

  lines.push('# Environment Variables');
  lines.push(`# Generated by env-doctor on ${new Date().toISOString().split('T')[0]}`);
  lines.push('# Uncomment and fill in the values below');
  lines.push('');

  for (const [key, def] of Object.entries(schema)) {
    const desc = def.description || '';
    const typeLabel = def.type;

    if (desc) {
      lines.push(`# ${desc}`);
    }

    const constraints: string[] = [];
    if (def.required) constraints.push('required');
    if (def.type === 'enum' && def.values) constraints.push(`options: ${def.values.join(', ')}`);
    if (def.minLength !== undefined) constraints.push(`min ${def.minLength} chars`);
    if (def.maxLength !== undefined) constraints.push(`max ${def.maxLength} chars`);
    if (def.default !== undefined) constraints.push(`default: ${def.default}`);

    if (constraints.length > 0) {
      lines.push(`# Type: ${typeLabel} \u2014 ${constraints.join(', ')}`);
    } else {
      lines.push(`# Type: ${typeLabel}`);
    }

    const example = def.example || (def.type === 'string' ? 'your-value' : def.type === 'number' || def.type === 'port' ? '1234' : def.type === 'url' ? 'https://example.com' : def.type === 'email' ? 'user@example.com' : def.type === 'boolean' ? 'true' : def.type === 'enum' && def.values ? def.values[0] : def.type === 'json' ? '{}' : 'your-value');

    if (def.required) {
      lines.push(`${key}=${example}`);
    } else if (def.default !== undefined) {
      lines.push(`# ${key}=${example} (default: ${def.default})`);
    } else {
      lines.push(`# ${key}=${example}`);
    }

    lines.push('');
  }

  const content = lines.join('\n');
  const resolvedPath = outputPath || '.env.example';

  if (outputPath !== '__test__') {
    fs.mkdirSync(path.dirname(path.resolve(resolvedPath)), { recursive: true });
    fs.writeFileSync(path.resolve(resolvedPath), content, 'utf-8');
  }

  return content;
}
